### ISSUE TITLE
Should using VPN cause remotedev-server to not work?

### ISSUE THREAD

**Issue by ghoshabhi** [zalmoxisus/remote-redux-devtools#113]
I am using a VPN connection to connect to my company's private network. Can this cause the remotedev server to break? I get the following error:

```
yarn run v1.3.2
$ remotedev --hostname=localhost --port=8000
[RemoteDev] Start server...
--------------------------------------------------------------------------------

   [Busy] Launching SocketCluster
1525113923224 - Origin: Worker (PID 17226)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/Users/abghosh/workspace/transporter-mobile/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/Users/abghosh/workspace/transporter-mobile/node_modules/uws/uws.js:42:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at SCServer (/Users/abghosh/workspace/transporter-mobile/node_modules/socketcluster-server/scserver.js:98:18)
1525113923230 - Worker 0 exited - Exit code: 1
```

Here's my config:
```
import devTools from 'remote-redux-devtools';

const enhancer = compose(
    applyMiddleware(thunk),
    devTools({
      name: 'app_name',
      realtime: true,
      hostname: 'localhost',
      port: 8000, // pointing to local remotedev server
    }),
    autoRehydrate(),
  );

const store = createStore(reducers, enhancer);
```

**Comment by Radi-Mortada** [comment]
I don't think so, but the fix is in here
https://github.com/zalmoxisus/remotedev-server/issues/58
