### ISSUE TITLE
Socket hung up error trying to run node-counter example

### ISSUE THREAD

**Issue by atrich** [zalmoxisus/remote-redux-devtools#144]
Synced latest, ran npm i on examples/node-counter, and tried to run with the react devtools extension running.

Modified to specify local server:
var store = createStore(counter, devTools({name: "test", hostname:"localhost", port:8000, realtime: true, secure: false}))

And am using the chrome devtools extension. This is on Windows 10.

Error log from running the example app:

```
C:\Repos\remote-redux-devtools\examples\node-counter>node index.js
1
2
remote-redux-devtools: Socket connection errors are being suppressed.
This can be disabled by setting suppressConnectErrors to 'false'.
{ SocketProtocolError: Socket hung up
    at SCClientSocket._onSCClose (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\socketcluster-client\lib\scclientsocket.js:632:15)
    at SCTransport.<anonymous> (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\socketcluster-client\lib\scclientsocket.js:304:12)
    at SCTransport.Emitter.emit (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\component-emitter\index.js:133:20)
    at SCTransport._onClose (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\socketcluster-client\lib\sctransport.js:217:28)
    at WebSocket.SCTransport.wsSocket.onerror (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\socketcluster-client\lib\sctransport.js:81:12)
    at WebSocket.onError (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (C:\Repos\remote-redux-devtools\examples\node-counter\node_modules\ws\lib\websocket.js:554:15)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
  name: 'SocketProtocolError',
  message: 'Socket hung up',
  code: 1006 }
```

**Comment by atrich** [comment]
Sorry - didn't realize I also needed to run the redux-devtools server. For anyone else who is trying this basic stuff, npm i -g redux-devtools-cli  and then run redux-devtools --hostname=localhost --port=8000
