### ISSUE TITLE
Devtools freezes and gives Cannot read property 'type' of undefined error

### ISSUE THREAD

**Issue by nitimmerman** [zalmoxisus/remote-redux-devtools#93]
Hi @zalmoxisus,

We are using your awesome tool to inspect our ngrx application.
However it happens quite often that the tool gives us errors in the developer window and doesn't repond to anything anymore. Sometimes if we kill chrome and start the application again. it is working again but other times it doesn't -> very annoying...

Could you please have a look into these errors?
It might have someting todo with the fact that we are composing our store at runtime. so when a module is lazy loaded, the corresponding branch of the state is attached to the existing state.

Here are the errors we get:
TypeError: Cannot read property 'type' of undefined
and Uncaught TypeError: Cannot read property 'replaceChild' of null

Full stacktrace of both of them:

window.html#panel:1 Error in response to runtime.getBackgroundPage: TypeError: Cannot read property 'type' of undefined
    at ActionListRow.value (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:49:14326)
    at u._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:22:31867)
    at u._renderValidatedComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:22:31994)
    at u.performInitialMount (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:22:27813)
    at u.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:22:26859)
    at Object.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:2:3297)
    at ReactDOMComponent.mountChildren (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:23:27010)
    at ReactDOMComponent._createInitialChildren (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:23:8824)
    at ReactDOMComponent.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:23:6892)
    at Object.mountComponent (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:2:3297)
    at Object.<anonymous> (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:52:30278)
    at __webpack_require__ (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:1:125)
    at Object.<anonymous> (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:1:605)
    at __webpack_require__ (chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:1:125)
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:1:284
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/window.bundle.js:1:307
window.bundle.js:2 Uncaught TypeError: Cannot read property 'replaceChild' of null
    at Function.replaceChildWithTree (window.bundle.js:2)
    at Object.dangerouslyReplaceNodeWithMarkup [as replaceNodeWithMarkup] (window.bundle.js:22)
    at u._replaceNodeWithMarkup (window.bundle.js:22)
    at u._updateRenderedComponent (window.bundle.js:22)
    at u._performComponentUpdate (window.bundle.js:22)
    at updateComponent (window.bundle.js:22)
    at u.receiveComponent (window.bundle.js:22)
    at Object.receiveComponent (window.bundle.js:2)
    at Object.updateChildren (window.bundle.js:22)
    at ReactDOMComponent._reconcilerUpdateChildren (window.bundle.js:23)

**Comment by zalmoxisus** [comment]
So it freezes the extension not your app right? Can you try if it is replicated with another monitor? If it was `Inspector`, try to choose `Log monitor` from the selector on the top.
