### ISSUE TITLE
Hanging + out of memory error

### ISSUE THREAD

**Issue by ssynix** [zalmoxisus/remote-redux-devtools#98]
I'm using `remote-redux-devtools` with `remotedev-server`, and *sometimes* when I have the redux-dev page open (e.g. `localhost:${remotedev_port}`), the page slows down to a crawl and eventually hangs/freezes.

I tried opening the page with Chrome DevTools open, and no logs were printed in the console. However, after a while Chrome paused my debugger before a potential out of memory crash.

This is what I see in `remotedev-server` logs:
> connected to remotedev-server
1505773053566 - Origin: Worker (PID 29)
   [Warning] SocketProtocolError: Client pong timed out
    at SCSocket._onSCClose (/usr/local/lib/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:205:17)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:170:10)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
1505773403833 - Origin: Worker (PID 29)
   [Warning] SocketProtocolError: Client pong timed out
    at SCSocket._onSCClose (/usr/local/lib/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:205:17)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/remotedev-server/node_modules/socketcluster-server/scsocket.js:170:10)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

Reopening the Chrome tab works, until it freezes/crashes again.

I see no impact on the NodeJS server that's dispatching the actions, or the redux devtools extension that's monitoring the front-end's store.

**Comment by damienwebdev** [comment]
Just chiming in that I'm seeing a similar thing in Chrome as well as Firefox.

**Comment by ghasemikasra39** [comment]
Exactly the same issue:
 
![image](https://user-images.githubusercontent.com/24314029/64470556-567ff900-d15a-11e9-9b09-30aa41a59b8c.png)

**Comment by anasanzari** [comment]
any update?

**Comment by ghasemikasra39** [comment]
Any update? still waiting :(

**Comment by kyranjamie** [comment]
Just landed here, still issues with `"@redux-devtools/remote": "0.7.5",`
